services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: "production"
      TOKEN: ${TOKEN}
      # Use the service name ‘db’ as the host
      # DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    # depends_on:
    #   db:
    #     condition: service_healthy
    restart: unless-stopped
    volumes:
      - bot-data:/var/app_data

  # db:
  #   image: postgres:16-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10
  #   volumes:
  #     - postgres:/var/lib/postgresql/data

volumes:
  # postgres:
  bot-data:
